name: buildpack-deps

permissions:
  packages: write
  pull-requests: write

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'scripts/docker/buildpack-deps/Dockerfile.emscripten'

jobs:
  buildpack-deps:
    runs-on: ${{ matrix.runs-on }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: buildpack-deps

    strategy:
      fail-fast: false
      matrix:
        include:
          - image_variant: emscripten
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0


      - name: Upgrade ${{ env.IMAGE_NAME }}-${{ matrix.image_variant }}
        run: |
          scripts/ci/docker_upgrade.sh ${{ env.IMAGE_NAME }} ${{ matrix.image_variant }}

